# Categorize donut output

- Read dfs and concatenate donut outputs of receipts
- Get embeddings the product name outputs of donut processed receipts
- Cosine similarity to the embeddings of full product names
-

In [1]:
import pandas as pd
import pickle

In [2]:
with open('../data/donut_output.pkl', 'rb') as f:
    donut_output = pickle.load(f)

In [4]:
donut_output[0]

,store_name,store_addr,telephone,date,time,subtotal,tax,total,ignore,tips,item_name,item_value,item_quantity,total_sum_check,receipt_id
0,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,VEONEASALAMI,4.77,1,SUM not found,Rewe6.jpg
1,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,"Rothstb301,59",1.49,1,SUM not found,Rewe6.jpg
2,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,VEPOWHERSCHE,1.99,1,SUM not found,Rewe6.jpg
3,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,Ratht300,1.99,1,SUM not found,Rewe6.jpg
4,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,BIODINCH:WAPS,2.58,1,SUM not found,Rewe6.jpg
5,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,GENUSSSHIETEN,1.59,1,SUM not found,Rewe6.jpg
6,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,VEGSPICKEN,1.89,1,SUM not found,Rewe6.jpg
7,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,GRANVAPIER,1.89,1,SUM not found,Rewe6.jpg
8,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,BRATPRINKGD,1.50,1,SUM not found,Rewe6.jpg
9,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,WENSOSPILS,0.95,1,SUM not found,Rewe6.jpg
10,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,PAND.0.8EUR,0.88,1,SUM not found,Rewe6.jpg
11,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,MENINGERHELL,0.99,1,SUM not found,Rewe6.jpg
12,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,PFANO.0.8EUR,0.88,1,SUM not found,Rewe6.jpg
13,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,FANTALEMON,1.19,1,SUM not found,Rewe6.jpg
14,REWEMarkET,06713Grathtainchen,03495389960,,15:20,,,,,,PFANO.25EURO,0.25,1,SUM not found,Rewe6.jpg

In [15]:
df_donut_output = pd.concat(donut_output).reset_index(drop=True)

In [16]:
df_donut_output.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   store_name       174 non-null    object
 1   store_addr       174 non-null    object
 2   telephone        174 non-null    object
 3   date             174 non-null    object
 4   time             174 non-null    object
 5   subtotal         174 non-null    object
 6   tax              174 non-null    object
 7   total            174 non-null    object
 8   ignore           174 non-null    object
 9   tips             174 non-null    object
 10  item_name        174 non-null    object
 11  item_value       170 non-null    object
 12  item_quantity    174 non-null    object
 13  total_sum_check  142 non-null    object
 14  receipt_id       174 non-null    object
dtypes: object(15)
memory usage: 20.5+ KB

In [17]:
df_donut_output[df_donut_output.item_value.isnull()]

,store_name,store_addr,telephone,date,time,subtotal,tax,total,ignore,tips,item_name,item_value,item_quantity,total_sum_check,receipt_id
48,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,StearXMeito,NaN,1,NaN,Rewe4.jpg
76,REWE,,0393535960960,,,,,,,,Stewer,NaN,1,SUM not found,Rewe3.jpg
102,REWE REWE,,0395338900,,19:41,,,37.98 37.98 37.98,,,Geg.VISA,NaN,1,False,Rewe9.jpg
140,REWE,,039356890960,,19:11,,,,,,Stewer,NaN,1,SUM not found,Rewe14.jpg

In [18]:
df_donut_output[df_donut_output.total_sum_check.isnull()]

,store_name,store_addr,telephone,date,time,subtotal,tax,total,ignore,tips,item_name,item_value,item_quantity,total_sum_check,receipt_id
23,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,KUSTSNBRO,0.63,1,NaN,Rewe4.jpg
24,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,KARTOFFEEBROY,0.19,1,NaN,Rewe4.jpg
25,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,KIKEBISKFNBROT,0.30,1,NaN,Rewe4.jpg
26,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,KIENBIKERNROT,1.07,1,NaN,Rewe4.jpg
27,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,KIENBIKERNROT,0.32,1,NaN,Rewe4.jpg
28,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,KISCHEIBEN,1.07,1,NaN,Rewe4.jpg
29,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,GENISSCHEIBEN,0.32,1,NaN,Rewe4.jpg
30,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,GENISSCHEIBEN,0.32,1,NaN,Rewe4.jpg
31,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,SKALTGRAHAPPL,1.07,1,NaN,Rewe4.jpg
32,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,MALATGUKE,1.07,1,NaN,Rewe4.jpg
33,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,MARCARINE,0.32,1,NaN,Rewe4.jpg
34,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,JAWEVIZENEH,2.99,1,NaN,Rewe4.jpg
35,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,DINNEWILLARY,0.90,1,NaN,Rewe4.jpg
36,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,PISNERJEVER,3.87,1,NaN,Rewe4.jpg
37,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,"[{'item_quantity': '1'}, {'item_key': '', 'ite...",1.50,1,NaN,Rewe4.jpg
38,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,LERGNWVST,-1.60,1,NaN,Rewe4.jpg
39,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,LERGNWVST,-1.60,1,NaN,Rewe4.jpg
40,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,LERGNWVST,-1.60,1,NaN,Rewe4.jpg
41,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,LERGNWVST,-1.60,1,NaN,Rewe4.jpg
42,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,LERGNWVST,-1.60,1,NaN,Rewe4.jpg
43,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,20StKX00,-1.50,1,NaN,Rewe4.jpg
44,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,LERGNWVST,38.00,1,NaN,Rewe4.jpg
45,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,SUMME,40.00,1,NaN,Rewe4.jpg
46,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,Geg.BAR,2.00,1,NaN,Rewe4.jpg
47,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,RockgeldBAR,2.00,1,NaN,Rewe4.jpg
48,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,StearXMeito,NaN,1,NaN,Rewe4.jpg
49,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,B:7.13,1.72,1,NaN,Rewe4.jpg
50,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,24.54,3.33,1,NaN,Rewe4.jpg
51,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,1.72,38.00,1,NaN,Rewe4.jpg
52,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,FSVDajExHxfExHxfNduthsRSFN,1.72,1,NaN,Rewe4.jpg
53,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,13:51mptur,,,NaN,Rewe4.jpg
54,REWE,06713GoraeiaInchen,034935-8960,,,,,38.00,,,ISS-Sigustar,,,NaN,Rewe4.jpg

In [19]:
df_donut_output.iloc[37].item_name

[{'item_quantity': '1'},
 {'item_key': '', 'item_quantity': '1'},
 {'item_key': '', 'item_quantity': '1'},
 {'item_key': '', 'item_quantity': '1'},
 {'item_key': ''}]

In [22]:
#df_donut_output.to_csv('../data/donut_output_uncleaned.csv')